apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: n test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout
      - uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
